### PR TITLE
Update code_of_conduct.md

### PR DESCRIPTION
**Pull request by burrrata**
## Statement of Intent

The wording of " individual teams" is a little bit ironic. Edited out that second sentence.

Also created a few changes to that section to make it flow better. I think the general message is the same, just more concise. Feel free to change though if there's anything else you think should be added/changed :)

## Code of Conduct

Changed the last sentence to:
- "By the nature of our decentralized space, the adoption of this code of conduct will be voluntary. It is up to Aragon Cooperative members to identify, discuss, and enforce consequences when inappropriate conduct occurs. "

## Feedback 

We don't have a documentation working group. I don't think we're ready for one yet. Removed that sentence.

It makes sense to have a place to keep this stuff. I think the simplest way to do that is to create a `docs` folder in the temp repo, then move all this stuff in there. That way the current Meta Proposal process can be used to amend the current CoC or whatever else. 

I think it would be good to have a place/way for people to discretely provide feedback on inappropriate conduct and get it resolved. The Ethereum Magicians had lots of thoughts on this, but I don't know if any materialized. For our purposes, maybe it makes sense to have a few designated "community managers" who can help resolve disputes and address inappropriate conduct? 

<br>

Otherwise everything looks good for an initial CoC doc.

### CODE REVIEW

**Comment by pythonpete32** [comment]
> It makes sense to have a place to keep this stuff. I think the simplest way to do that is to create a docs folder in the temp repo

That makes the most sense, I started working on this before #26 passed ill merge these docs then make a pr to temp

> For our purposes, maybe it makes sense to have a few designated "community managers" who can help resolve disputes and address inappropriate conduct?

Definitely, my initial thoughts around this as well as on/offboarding were to have a council. But the more I think about it, the more uncomfortable i feel about how complicated the checks and balances need to be

**Comment by burrrata** [comment]
Let's wait to make a PR until we're ready to put it to a vote.

Until then I'd recommend refining the drafts here, then once they're ready posting them in the open Issue in temp, and after discussion with the broader group editing the proposals, creating a PR, and creating a vote to merge the PR

**Comment by burrrata** [comment]
>> For our purposes, maybe it makes sense to have a few designated "community managers" who can help resolve disputes and address inappropriate conduct?

> Definitely, my initial thoughts around this as well as on/offboarding were to have a council. But the more I think about it, the more uncomfortable i feel about how complicated the checks and balances need to be

Yeah the struggle is real. It's not an easy problem to solve. Maybe worth reaching out to the A1 team to see how they do it. I think @light does a lot of that stuff, but honestly I'm not sure

**Comment by pythonpete32** [comment]
> Maybe worth reaching out to the A1 team to see how they do it.

Probably a good idea to reach out anyway, but A1 doesn't really have that problem. The A1 team is small, highly cohesive, with high trust. We are larger, less cohesive. Even small imbalances in power dynamics can have massive adverse effects. 

But this is why it's so interesting to work on

**Comment by burrrata** [comment]
> But this is why it's so interesting to work on

Ditto :)
Governance when everyone gets along is easy. It's when there's disagreements that you can see if your governance structure actually works as intended lol

**Pull request merged**
